# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        script: # This will pull all branches from bitbucket and push all to github
          - git branch -r | grep -v '\->' | while read remote; do git branch --track "${remote#origin/}" "$remote"; done
          - git fetch --all
          - git pull --all
          - git remote add github git@github.com:vlocityinc/newport-design-system.git
          - git push --mirror github
